name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies and run tests for client
      run: |
        cd client
        poetry install
        poetry run pytest

    - name: Install dependencies and run tests for master
      run: |
        cd master
        poetry install
        poetry run pytest

    - name: Install dependencies and run tests for slave
      run: |
        cd slave
        poetry install
        poetry run pytest
